### ISSUE TITLE
Sync script fails silently if aws call fails

### ISSUE THREAD

**Issue by kaipak** [NASA-PDS/web-analytics#12]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Current iteration of sync script fails silently if something is wrong with CLI command (e.g., if current token has expired). Add error checking to make script fail gracefully with useful output and log message.

### 🕵️ Expected behavior

Script should fail gracefully and with a useful output.

**Comment by kaipak** [comment]
Work in progress.

**Comment by jordanpadams** [comment]
Workaround: Document manual check that logs have been loaded.

**Comment by kaipak** [comment]
This issue is reopened. Plan on resolving by end of week.

**Comment by kaipak** [comment]
PR submitted to resolve issue.

**Comment by jordanpadams** [comment]
Skipping I&T. Internal app that is not in production
