### ISSUE TITLE
Map special characters in Athena/Presto SQL queries before dataset creation in QS.

### ISSUE THREAD

**Issue by kaipak** [NASA-PDS/web-analytics#13]
### Checked for duplicates

No - I haven't checked

### 💪 Motivation

...so that I can [why do you want to do this?]

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
Requires Jupyter Notebooks. See DSIO-4172

**Comment by kaipak** [comment]
@foxydata6 has come up with solution to implement arbitrary Python code to handle this work and export as CSV/Parquet files.
