### ISSUE TITLE
As a user, I want year over year metrics for total egress

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/web-analytics#21]
### Checked for duplicates

Yes

### 🧑‍🔬 User Persona(s)

Managers

### 💪 Motivation

...so that I can [why do you want to do this?]

### 📖 Additional Details

- [ ] By Node
- [ ] Global PDS
- [ ] Bots vs. "people"

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by kaipak** [comment]
@foxydata6 , I think most of these views are complete already. Let's work with PDS team to make sure we have requirements covered.

**Comment by jordanpadams** [comment]
Done. See current dashboard
