### ISSUE TITLE
As a user, I want a mission-specific dashboard showing instrument and product type download metrics

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/web-analytics#24]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Node Operator, PI

### 💪 Motivation

...so that I can know how much and who is downloading our mission data

### Acceptance Criteria

**Given** mission Mars 2020 dashboard
**When I perform** a review of the dashboard 
**Then I expect** to see breakdowns of:
* files downloaded, MB downloaded, number of unique users by bundle
* visualization / table of users / locations downloading the data
* bots vs. people

### ⚙️ Engineering Details
This will requiring keying off of each node website where the data lives, finding the directory where the data resides, and showing the download. Attached is an example from June we should shoot to be close to for the download metrics.

Here is the breakdown by LID / Node:
<img width="379" alt="Screenshot 2023-08-17 at 9 29 47 AM" src="https://github.com/NASA-PDS/web-analytics/assets/33492486/20c92597-012b-4406-8020-14547fa038d1">

[Mars2020_Usage_Metrics_IMG-June-2023.xlsx](https://github.com/NASA-PDS/web-analytics/files/12371645/Mars2020_Usage_Metrics_IMG-June-2023.xlsx)

URLs to data:
* https://planetarydata.jpl.nasa.gov/img/data/m2020/public/
* https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/Mars2020/
* https://pds-geosciences.wustl.edu/m2020/

**Comment by jordanpadams** [comment]
@foxydata6 @kaipak were we able to work on this at all?

**Comment by kaipak** [comment]
@foxydata6 says "all of the missions we talked about last week should be in the dashboard now"

**Comment by jordanpadams** [comment]
This has all been completed and are loaded into existing dashboards.

![Uploading Screenshot 2024-06-04 at 1.15.00 PM.png…]()

**Comment by jordanpadams** [comment]
Skipping I&T. Internal app that is not in production
