### ISSUE TITLE
Automate Log Sync to S3 and Athena

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/web-analytics#30]
### 💡 Description

Complete the necessary updates in order to automate the syncing of the logs from our on-prem system. Also investigate what it might take to move the entire Report Manager execution to the cloud.

### ⚔️ Sub-tasks

- [x] setting scripts with service account
- [x] set up cronjob

**Comment by kaipak** [comment]
@kaipak will run one-off sync run from reporting server to get latest data for @foxydata6 reporting work this week ending March 28, 2024.

**Comment by kaipak** [comment]
Service account has been set up for this. Will configure cron and close out work by end of tomorrow.

**Comment by c-suh** [comment]
I've set up conda, awscli, and this repo on the service account. I am figuring out the part for AWS authentication, as the repo we were using with our personal accounts is not applicable to the service account.

**Comment by kaipak** [comment]
Thanks for picking up on this!

**Comment by c-suh** [comment]
Script runs as expected on the service account! Am working on setting up the cronjob and saving the output.
