### ISSUE TITLE
Document Strategy for Web Analytics System Migration to MCP

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/web-analytics#32]
### 💡 Description

We need to understand what we will need to do in order to migrate our existing web analytics system to MCP.

**Comment by kaipak** [comment]
In progress. First draft to be finished by end of the week.

**Comment by kaipak** [comment]
@jordanpadams , is there a specific format this should be in? Maybe the Wiki?

**Comment by jordanpadams** [comment]
@kaipak correct. this is the lowest priority of the tasks in the backlog for this web analytics. we can punt this over to other folks when we get to this migration, if needed.

**Comment by kaipak** [comment]
All relevant project documentation will be centralized here: https://wiki.jpl.nasa.gov/display/PDSEN/PDS+Web+Analytics
